apiVersion: v1
kind: ReplicationController
metadata: 
  name: myweb-rc
spec: 
  replicas: 3
  selector: 
    env: production
  template: 
    metadata: 
      labels: 
        dc: "2"
        env: production
        region: IN
      name: myweb-pod
    spec: 
      containers: 
        - 
          image: httpd
          name: myweb-con
